name: Tests

on:
    pull_request:
        branches: ["*"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Run Linter
              run: npm run lint
              continue-on-error: true
            - name: Build packages
              run: npm run build
            - name: Lost Pixel
              uses: lost-pixel/lost-pixel@v3.2.0
